= Aan de slag

Als ontwikkelaar kun je direct starten met het aansluiten op de {apiname}:

1. Bekijk de functionaliteit en technische specificaties
2. Download de OpenAPI-specificaties en de JSON-schema's
3. Bouw de aansluiting op de {apiname} en test deze via de demo-omgeving.
4. Sluit aan op de proefomgeving en doorloop de compliancytesten (Schouwen en Toetsen).
5. Je bent klaar voor productie!

== Stap 1 - Bekijk de functionaliteit en specificaties

De OpenAPI specificatie van deze API is opgenomen in de repository en is ook als grafische weergave in te zien middels Redocly.
Hier zijn ook de JSON-schema's opgenomen die beschrijven hoe de berichten zijn opgebouwd en welke gegevens deze bevatten.

* OpenAPI Schema
** Sources: https://github.com/rvig-brp/BRP-Berichten-API/tree/main/openapi-specificatie[window=_blank]
** Grafische weergave: https://brp-berichten-api.dictua.ictu-sr.nl/openapi/berichten-api.html[window=_blank]

Middels het {lo-naam-voluit} ({lo-naam-afgekort}) kun je meer context krijgen over hoe deze berichten worden gebruikt en welke berichtcycli daarbij betrokken zijn.


* {lo-naam-voluit}
** Als webpagina: https://developer.rvig.nl/lo-brp/LO-BRP/[window=_blank]
** Als PDF: https://www.rvig.nl/lo-brp[window=_blank]

Veel berichten zijn gerelateerd aan persoonslijsten.
Deze zijn opgebouwd volgens een JSON-structuur die aansluit op het {lo-naam-afgekort}.
De opbouw hiervan wordt toegelicht via:

* xref:ROOT:attachment$PLstructuur_in_json/readPL.html["https://github.com/rvig-brp/BRP-Berichten-API/blob/main/JSON-PL/documentatie_onderbouwing/readPL.html",window=_blank]


== Stap 2 - Download de OpenAPI specificaties

Download de specificaties en de bijbehorende JSON-schema's via:

* https://github.com/rvig-brp/BRP-Berichten-API/tree/main/openapi-specificatie[window=_blank]

== Stap 3 - Bouw de aansluiting op de {apiname} en test deze via de demo-omgeving.

Om te integreren met de {apiname} ontwikkel je een client.
Om je in een vroeg stadium bekend te laten raken met de {apiname} is een demo-omgeving beschikbaar.
In deze omgeving:

* Kun je zonder Diginetwerk verbinding maken
* Kun je zonder gevolgen testen en experimenteren
* Kun je zelf bepalen namens welke organisaties je berichten verstuurt en ontvangt.

Hiermee raak je bekend met het koppelvlak en kun je jouw client-implementatie stap voor stap ontwikkelen en testen.

include::ROOT:partial$demo-omgeving-waarschuwing.adoc[]

1. Lees hoe het verzenden en ontvangen van berichten werkt zodat je vooraf weet wat je kunt verwachten.
2. Zorg dat je client voldoet aan de OpenAPI-specificatie en de JSON-schema's.
3. Vraag toegang aan tot de demo-omgeving van de {apiname} via {rvig-email}.
4. Test via de demo-omgeving of je client berichten kan verzenden en ontvangen.
Gebruik eventueel de beschikbare {github-url}/tree/main/voorbeelden/berichten[voorbeeldberichten, window=_blank].

Heb je deze stappen afgerond? Dan kun je verder met aansluiten op de proefomgeving.

== Stap 4 - Aansluiten op de proefomgeving

De proefomgeving is een ketentestomgeving waarin je jouw client test in een realistische situatie.
Je wisselt hier daadwerkelijk berichten uit met de BRP(-V).
Je authenticeert hier via je eigen afnemerId en communiceert daarmee met de BRP(-V) net zoals dit in de productieomgeving zou gebeuren.

Samen met het {testafdeling-naam} van RvIG doorloop je deze fase.
Deze wordt afgesloten met een compliancy-test (voorheen Schouwen en Toetsen).
Hierbij wordt vastgesteld of de verwerking door je software van de berichten en de volgorde en de inhoud van de gegevens verklaarbaar is aan de hand van het {lo-naam-afgekort}.
Na een succesvolle afronding kan jouw aansluiting worden voorbereid op de productieomgeving.

Meer informatie over het aansluiten op de proef- en productieomgeving en de compliancy-test (Schouwen en Toetsen) staat xref:concept/schouwen-en-toetsen.adoc[hier] beschreven.
