= Welkom bij de {apiname}

Sinds 1992 wisselen gemeenten en afnemers persoonsgegevens uit via de BRP-berichtendienst.
Jaarlijks worden ongeveer 185 miljoen berichten via deze dienst verstuurd.
Het BRP-berichtenverkeer verloopt op dit moment nog via de mailboxserver en de webservice StuurGBAbericht.
Deze worden beide vervangen door de {apiname}.

Het vervangen van de mailboxserver is nodig om ervoor te zorgen dat het BRP-berichtenverkeer ook in de toekomst betrouwbaar en veilig blijft functioneren.
De mailboxserver wordt beheerd door een externe leverancier.
Het contract hiervoor kan niet langer worden verlengd.
Bovendien gebruikt de mailboxserver verouderde technologie, wat op termijn risico’s met zich meebrengt voor de continuïteit en beveiliging van de dienstverlening.

De {apiname} is gebaseerd op moderne en gangbare technologische standaarden, zoals:

* REST API (een standaard voor het transporteren van gegevens);
* JSON (een standaard voor het structureren van berichten);
* UTF-8 (een standaard voor het coderen van tekens).

Meer informatie vind je op: https://www.rvig.nl/vervanging-mailboxserver[window=_blank]

== Context

=== De BRP

De Basisregistratie Persoonsgegevens (BRP) is een landelijke registratie van personen die in gemeenten, in de Registratie Niet-Ingezetenen (RNI) en bij de openbare lichamen Bonaire, Sint Eustatius en Saba ingeschreven zijn.

De BRP wordt decentraal "bijgehouden".
Dat wil zeggen dat persoongegevens vastgelegd worden bij de zogenaamde "bijhouders", zoals gemeenten en de RNI.
Vervolgens wordt dit gesynchroniseerd met de landelijke Basisregistratie Personen Verstrekkingsvoorziening (BRP-V).

Alle overheidsorganisaties en bestuursorganen zijn voor de uitvoering van hun wettelijke taken verplicht om gebruik te maken van de persoonsgegevens in de BRP.
De communicatie tussen de systemen van deze overheidsinstellingen en bestuursorganen vindt geautomatiseerd plaats via webservices, API's en de BRP-berichtendienst.

=== Berichten gerelateerd aan de BRP

Om het BRP-stelsel te laten functioneren zijn er afspraken gemaakt over de uitwisseling van informatie tussen bijhouders, de BRP en afnemers.
Deze afspraken zijn vastgelegd in het {lo-naam-voluit} ({lo-naam-afgekort}).
In het {lo-naam-afgekort} zijn bericht-cycli beschreven waarin per bericht wordt aangegeven wat het doel van een dergelijk bericht is en welke gegevens deze bevat.
Deze berichten worden uitgewisseld via de BRP-berichtendienst.

=== De BRP-berichtendienst

Met de BRP-berichtendienst wordt het geheel van applicaties en koppelvlakken bedoeld dat de a-synchrone uitwisseling van BRP-berichten tussen overheidsorganisaties en bestuursorganen mogelijk maakt.
Op dit moment zijn er drie manieren om berichten uit te wisselen:

* via de mailboxserver
* via de webservice StuurGBAbericht
* via de {apiname}

=== De {apiname}

De {apiname} vervangt stapsgewijs de bestaande voorzieningen. Eerst wordt de mailboxserver vervangen, gevolgd door de webservice StuurGBAbericht.

Ontwikkelaars van (ICT-leveranciers van) overheidsorganisaties en bestuursorganen kunnen de documentatie van deze website gebruiken om hun applicaties aan te passen en over te stappen op de {apiname}.

== Wat vind je op dit portaal?

Op dit portaal voor ontwikkelaars vind je onder andere:

* Handleidingen: praktische informatie die helpt bij het implementeren van de {apiname} in je applicatie.
* Concepten: uitleg over functionele en technische onderwerpen die relevant zijn voor de {apiname}.
* Aansluitinstructies: informatie over het aansluiten op de {apiname} en bijbehorende processen.

== Contact

* Storing melden?
Neem contact op met de RvIG frontoffice: op werkdagen telefonisch bereikbaar tussen 08.30 en 12.00 uur en tussen 13.00 en 17.00 uur via 088-9001000. Vanuit het buitenland bel je naar: +31 707511000. Je kunt ook een e-mail sturen naar {rvig-email}
* Bug melden? {github-url}/issues[Maak een issue aan, window=_blank]
* Verbetersuggestie doen voor de {apiname} of de documentatie op dit portaal? {github-url}/issues[Maak een issue aan, window=_blank]
* Voor meer informatie en/of hulpvragen kun je contact opnemen via onderstaand e-mailadres: {rvig-email}
