= REST-API

De {apiname} is ontwikkeld als vervanger van de mailboxserver.
Bij het ontwerp van de API is ervoor gekozen om op verschillende onderdelen aan te sluiten bij de verwerking en terminologie van de mailboxserver.
Dit maakt de overstap naar de {apiname} voor aangesloten organisaties op de mailboxserver eenvoudiger.

== Resource

Binnen REST heeft een request normaal gesproken betrekking op één resource.
In de context van de {apiname} is een bericht een resource.
De {apiname} wijkt hier vanaf.
Deze ondersteunt het verwerken van meerdere berichten binnen één request.
Dit maakt het mogelijk om meerdere berichten tegelijk te verzenden, ontvangen en verwijderen.

In de response wordt vervolgens per bericht aangegeven wat de resultaten zijn.

== Spraakverwarring PUT != POST

Binnen de {apiname} worden termen gebruikt als getMessage, putMessage, listMessage.
Hoewel de getMessage ook daadwerkelijk met een HTTP GET uitgevoerd wordt, wordt de putMessage uitgevoerd middels een HTTP POST (en geen PUT).
De term putMessage is afkomstig uit het verleden, maar wel gehanteerd, maar heeft geen relatie met een HTTP PUT-methode.
