= Tekensets (UTF-8 / Teletex)

Binnen het BRP-stelsel is lange tijd gebruikgemaakt van de Teletex tekenset.
Berichten die via de mailboxserver en de webservice StuurGBAbericht werden uitgewisseld, waren in deze tekenset opgebouwd.
Met de introductie van de {apiname} wordt overgestapt op UTF-8.
UTF-8 is een moderne en breed ondersteunde standaard voor het coderen van tekens.

== Beperkingen binnen de UTF-8 tekenset.

WARNING: Hoewel de {apiname} de UTF-8 tekenset volledig ondersteund, stelt het {lo-naam-voluit} ({lo-naam-afgekort}) beperkingen aan de tekens die binnen het BRP-stelsel gebruikt mogen worden.

Hiervoor zijn meerdere redenen:

* Tijdens de overgangsperiode moeten berichten nog kunnen worden uitgewisseld met de mailboxserver en de webservice StuurGBAbericht;
* Niet alle aangesloten systemen ondersteunen de volledige UTF-8 tekenset;
* Het {lo-naam-afgekort} stelt welke tekens binnen berichten gebruikt mogen worden.

Gebruik uitsluitend de tekens die binnen het {lo-naam-afgekort} zijn toegestaan.
Lees meer over de toegestane tekens in het {lo-naam-afgekort}: +
https://developer.rvig.nl/lo-brp/LO-BRP/#_tekenset[window=_blank]

Daarnaast zijn voorbeeldberichten beschikbaar waarin alle toegestane tekens zijn opgenomen.

* *Teletex*: +
https://github.com/rvig-brp/BRP-Berichten-API/blob/main/voorbeelden/berichten/Vb01_alle-tekens-teletex.GBA[window=_blank]
* *UTF-8*: +
https://github.com/rvig-brp/BRP-Berichten-API/blob/main/voorbeelden/berichten/Vb01_alle-tekens-utf8.GBA[window=_blank]

## Teletex

De Teletex standaard is gebaseerd op de internationale standaard 'CCITT-aanbeveling T.61'.
Binnen de {apiname} speelt deze tekenset vrijwel geen rol.
Teletex is alleen nog relevant bij het converteren van berichten tussen het oude en het nieuwe formaat.
Dit gebeurt via de functionaliteit voor berichtenconversie binnen de {apiname}.
Meer informatie hierover staat op de pagina: xref:handleiding/berichten-converteren.adoc[].

Lees meer over de Teletex tekenset:

* http://en.wikipedia.org/wiki/ITU_T.61[window=_blank]
* xref:ROOT:attachment$T-REC-T.61-198811.pdf[CCITT Recommendation T.61,window=_blank]
* https://developer.rvig.nl/lo-brp/LO-BRP/#_tekenset[window=_blank]

