= Aansluiten op de productie-omgeving

Nadat de compliancy-test (voorheen "Schouwen en Toetsen") succesvol is afgerond, kan je aansluiten op de productie-omgeving van de {apiname}.

Voor aansluiting op de productie-omgeving gelden de volgende voorwaarden:

* Een geldige afnemercode/afnemersindicatie (opgenomen in Tabel 35).
Dit is het nummer dat hoort bij het autorisatiebesluit van je organisatie.
** Deze vind je hier:
*** https://publicaties.rvig.nl/zoeken[window=_blank]
*** https://publicaties.rvig.nl/zoekpagina-tabel-35-autorisatietabel[window=_blank]

** Meer informatie staat op: xref:concept/autorisatie.adoc[]
* De compliancy-test (voorheen xref:concept/schouwen-en-toetsen.adoc["Schouwen en Toetsen"] is succesvol afgerond

* Aansluiting op xref:concept/diginetwerk.adoc[Diginetwerk]

* Je organisatie beschikt over een xref:concept/pki-overheid-certificaat.adoc[PKI-overheid certificaat] (met xref:concept/organisatie-identificatie-nummer.adoc[OIN])

* Je organisatie beschikt over OAuth2 credentials (client-id, client-secret en scope).
Deze kun je aanvragen via {rvig-email}.

De aansluitinstructies voor de productie-omgeving zijn beschikbaar via de website van RvIG:

* https://www.rvig.nl/Aansluitinstructies-Diginetwerk-voor-stelselapplicaties

== Controle OAuth2 credentials en JWT-token

Wij adviseren om de ontvangen OAuth2 credentials en het JWT-token na ontvangst te controleren op juistheid.
Informatie hierover staat op de volgende pagina:

* xref:handleiding/oauth2-token-controle.adoc[Controle OAuth2 credentials en JWT-token].
