= Aansluiten op de proefomgeving

Als je applicatie klaar is om te testen en je organisatie beschikt over een aansluiting op Diginetwerk, dan kun je bij RvIG een aansluiting aanvragen voor de proefomgeving van de {apiname}.

Voor aansluitingen op de proefomgeving gelden de volgende voorwaarden:

* Aansluiting op xref:concept/diginetwerk.adoc[Diginetwerk]

* xref:concept/pki-overheid-certificaat.adoc[PKI-overheid certificaat] (met xref:concept/organisatie-identificatie-nummer.adoc[OIN])

* Beschikking over OAuth2 credentials (client-id, client-secret en scope).
Deze zijn aan te vragen via RvIG.

Op de website van RvIG zijn de https://www.rvig.nl/Aansluitinstructies-Diginetwerk-voor-stelselapplicaties[aansluitinstructies] voor het aansluiten op de proefomgeving beschikbaar.

== Compliancy-test (voorheen "Schouwen en Toetsen")

Voordat je organisatie kan aansluiten op de productie-omgeving van de {apiname} moet je voldoen aan een compliancy-test
(voorheen "xref:concept/schouwen-en-toetsen.adoc[Schouwen en Toetsen]".
Het doel hiervan is vaststellen dat een systeem van een gemeente, afnemer of RvIG zelf naar systemen van andere organisaties aangesloten op de {apiname} conform het {lo-naam-voluit} ({lo-naam-afgekort}).

De compliancy-test wordt uitgevoerd in samenwerking met het {testafdeling-naam} van RvIG.
Op basis van de situatie van je organisatie ontvang je een draaiboek met een aantal relevante scenario's.
Na het uitvoeren van de scenario's beoordeelt het {testafdeling-naam} het resultaat en wordt vastgesteld of aansluiting op de productie-omgeving mogelijk is.

Een verzoek voor het uitvoeren van een compliancy-test kun je per e-mail sturen aan {rvig-email}

== Controle OAuth2 credentials en JWT-token

Wij adviseren om de ontvangen OAuth2 credentials en het JWT-token na ontvangst te controleren op juistheid.
Informatie hierover staat op de volgende pagina:

* xref:handleiding/oauth2-token-controle.adoc[Controle OAuth2 credentials en JWT-token].
